import type { Product } from '@/types/product'

/**
 * دادهٔ نمونهٔ فاز ۱ — ۲۴ محصول در ۶ دسته.
 *
 * نکات عمدی در طراحی این داده:
 *  - شبکهٔ سازگاری واقعی است: `consumables` هر دستگاه به `id` مصرفی‌های
 *    موجود اشاره می‌کند و `compatibleWith` مصرفی‌ها به `model` دستگاه‌ها.
 *    این همان دیتایی است که ویجت «یافتن قطعهٔ سازگار» در فاز ۲ مصرف می‌کند.
 *  - چند کالا عمداً `quote_only` هستند تا حالت «تماس بگیرید» تست شود.
 *  - هر چهار حالت موجودی پوشش داده شده است.
 *  - `compareAtPrice` فقط جایی آمده که تخفیف واقعی معنا دارد (نه ضرب در ۱.۲).
 */

const img = (c: string) => [`/products/${c}.svg`]

export const PRODUCTS: Product[] = [
  // ═══════════════ پرینتر ═══════════════
  {
    id: 'p-001',
    slug: 'canon-i-sensys-lbp-2900',
    brand: 'canon',
    model: 'i-SENSYS LBP-2900',
    name: 'پرینتر لیزری تک‌رنگ کانن مدل i-SENSYS LBP-2900',
    sku: 'CN-LBP2900',
    category: 'printer',
    priceType: 'fixed',
    price: 4850000,
    compareAtPrice: 5300000,
    stockStatus: 'in_stock',
    images: img('printer'),
    shortDescription:
      'پرینتر لیزری فشرده و کم‌مصرف، مناسب دفاتر کوچک و مصارف خانگی با کیفیت چاپ بالا.',
    keyFeatures: ['چاپ ۱۲ صفحه در دقیقه', 'رزولوشن ۶۰۰ در ۶۰۰', 'اتصال USB 2.0'],
    specs: [
      { key: 'سرعت چاپ', value: '12 ppm', group: 'عملکرد', isTechnical: true },
      { key: 'رزولوشن', value: '600 × 600 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'حافظه', value: '8 MB', group: 'عملکرد', isTechnical: true },
      { key: 'اتصالات', value: 'USB 2.0', group: 'اتصالات', isTechnical: true },
      { key: 'ظرفیت کاغذ', value: '۱۵۰ برگ', group: 'کاغذ' },
      { key: 'اندازهٔ کاغذ', value: 'A4، A5، B5', group: 'کاغذ', isTechnical: true },
    ],
    technology: 'laser',
    colorSupport: 'mono',
    usageClass: 'home',
    warrantyMonths: 18,
    condition: 'new',
    consumables: ['c-001', 'c-002'],
    isFeatured: true,
    isBestSeller: true,
    createdAt: '2026-05-12',
  },
  {
    id: 'p-002',
    slug: 'hp-laserjet-pro-m404dn',
    brand: 'hp',
    model: 'LaserJet Pro M404dn',
    name: 'پرینتر لیزری تک‌رنگ اچ‌پی مدل LaserJet Pro M404dn',
    sku: 'HP-M404DN',
    category: 'printer',
    priceType: 'fixed',
    price: 18900000,
    stockStatus: 'in_stock',
    images: img('printer'),
    shortDescription:
      'چاپگر اداری پرسرعت با قابلیت چاپ دورو خودکار و پورت شبکه، مناسب گروه‌های کاری متوسط.',
    keyFeatures: ['چاپ ۳۸ صفحه در دقیقه', 'دورو خودکار', 'پورت شبکه اترنت'],
    specs: [
      { key: 'سرعت چاپ', value: '38 ppm', group: 'عملکرد', isTechnical: true },
      { key: 'رزولوشن', value: '1200 × 1200 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'حافظه', value: '256 MB', group: 'عملکرد', isTechnical: true },
      { key: 'چاپ دورو', value: 'خودکار', group: 'عملکرد' },
      { key: 'اتصالات', value: 'USB 2.0، Ethernet 10/100/1000', group: 'اتصالات', isTechnical: true },
      { key: 'چرخهٔ کاری ماهانه', value: '80,000 صفحه', group: 'عملکرد', isTechnical: true },
    ],
    technology: 'laser',
    colorSupport: 'mono',
    usageClass: 'office',
    warrantyMonths: 24,
    condition: 'new',
    consumables: ['c-003'],
    isFeatured: true,
    isBestSeller: true,
    createdAt: '2026-06-02',
  },
  {
    id: 'p-003',
    slug: 'epson-ecotank-l3250',
    brand: 'epson',
    model: 'EcoTank L3250',
    name: 'پرینتر جوهرافشان چندکاره اپسون مدل EcoTank L3250',
    sku: 'EP-L3250',
    category: 'printer',
    priceType: 'fixed',
    price: 12400000,
    compareAtPrice: 13800000,
    stockStatus: 'low_stock',
    images: img('printer'),
    shortDescription:
      'چاپگر مخزن‌دار سه‌کاره با هزینهٔ چاپ بسیار پایین و اتصال بی‌سیم، مناسب خانه و دفتر کوچک.',
    keyFeatures: ['مخزن جوهر قابل شارژ', 'چاپ، کپی و اسکن', 'اتصال Wi-Fi و Wi-Fi Direct'],
    specs: [
      { key: 'سرعت چاپ', value: '10 ppm (مشکی)', group: 'عملکرد', isTechnical: true },
      { key: 'رزولوشن', value: '5760 × 1440 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'کارکرد', value: 'چاپ، اسکن، کپی', group: 'عملکرد' },
      { key: 'اتصالات', value: 'USB، Wi-Fi، Wi-Fi Direct', group: 'اتصالات', isTechnical: true },
      { key: 'ظرفیت کاغذ', value: '۱۰۰ برگ', group: 'کاغذ' },
    ],
    technology: 'inkjet',
    colorSupport: 'color',
    usageClass: 'home',
    warrantyMonths: 12,
    condition: 'new',
    consumables: ['c-004'],
    isFeatured: true,
    createdAt: '2026-06-18',
  },
  {
    id: 'p-004',
    slug: 'brother-hl-l2375dw',
    brand: 'brother',
    model: 'HL-L2375DW',
    name: 'پرینتر لیزری تک‌رنگ برادر مدل HL-L2375DW',
    sku: 'BR-L2375DW',
    category: 'printer',
    priceType: 'fixed',
    price: 15600000,
    stockStatus: 'in_stock',
    images: img('printer'),
    shortDescription:
      'چاپگر لیزری بی‌سیم با چاپ دورو خودکار، انتخابی مقرون‌به‌صرفه برای دفاتر کوچک.',
    keyFeatures: ['چاپ ۳۴ صفحه در دقیقه', 'اتصال بی‌سیم', 'چاپ دورو خودکار'],
    specs: [
      { key: 'سرعت چاپ', value: '34 ppm', group: 'عملکرد', isTechnical: true },
      { key: 'رزولوشن', value: '2400 × 600 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'حافظه', value: '64 MB', group: 'عملکرد', isTechnical: true },
      { key: 'اتصالات', value: 'USB، Ethernet، Wi-Fi', group: 'اتصالات', isTechnical: true },
    ],
    technology: 'laser',
    colorSupport: 'mono',
    usageClass: 'office',
    warrantyMonths: 24,
    condition: 'new',
    consumables: ['c-005'],
    createdAt: '2026-04-21',
  },
  {
    id: 'p-005',
    slug: 'hp-color-laserjet-pro-m454dw',
    brand: 'hp',
    model: 'Color LaserJet Pro M454dw',
    name: 'پرینتر لیزری رنگی اچ‌پی مدل Color LaserJet Pro M454dw',
    sku: 'HP-M454DW',
    category: 'printer',
    priceType: 'fixed',
    price: 46500000,
    stockStatus: 'in_stock',
    images: img('printer'),
    shortDescription:
      'چاپگر لیزری رنگی حرفه‌ای با کیفیت بالا برای چاپ اسناد بازاریابی و گزارش‌های سازمانی.',
    keyFeatures: ['چاپ رنگی ۲۸ صفحه در دقیقه', 'صفحه‌نمایش لمسی', 'امنیت سازمانی'],
    specs: [
      { key: 'سرعت چاپ', value: '28 ppm', group: 'عملکرد', isTechnical: true },
      { key: 'رزولوشن', value: '600 × 600 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'حافظه', value: '512 MB', group: 'عملکرد', isTechnical: true },
      { key: 'نمایشگر', value: 'لمسی ۲.۷ اینچ', group: 'رابط کاربری' },
      { key: 'اتصالات', value: 'USB، Ethernet، Wi-Fi', group: 'اتصالات', isTechnical: true },
    ],
    technology: 'laser',
    colorSupport: 'color',
    usageClass: 'enterprise',
    warrantyMonths: 24,
    condition: 'new',
    consumables: ['c-006'],
    isBestSeller: true,
    createdAt: '2026-07-01',
  },
  {
    id: 'p-006',
    slug: 'epson-lq-350-dot-matrix',
    brand: 'epson',
    model: 'LQ-350',
    name: 'پرینتر سوزنی اپسون مدل LQ-350',
    sku: 'EP-LQ350',
    category: 'printer',
    priceType: 'fixed',
    price: 21300000,
    stockStatus: 'out_of_stock',
    images: img('printer'),
    shortDescription:
      'چاپگر سوزنی ۲۴ سوزنه برای چاپ فاکتور و فرم‌های چندنسخه‌ای، مناسب انبار و حسابداری.',
    keyFeatures: ['۲۴ سوزن', 'چاپ فرم چندنسخه‌ای', 'دوام بالا'],
    specs: [
      { key: 'تعداد سوزن', value: '24 pin', group: 'عملکرد', isTechnical: true },
      { key: 'سرعت چاپ', value: '347 cps', group: 'عملکرد', isTechnical: true },
      { key: 'نسخهٔ همزمان', value: 'اصل + ۳ کپی', group: 'کاغذ' },
      { key: 'اتصالات', value: 'USB، Parallel، Serial', group: 'اتصالات', isTechnical: true },
    ],
    technology: 'dot_matrix',
    colorSupport: 'mono',
    usageClass: 'office',
    warrantyMonths: 12,
    condition: 'new',
    createdAt: '2026-03-08',
  },

  // ═══════════════ اسکنر ═══════════════
  {
    id: 's-001',
    slug: 'canon-imageformula-dr-c225',
    brand: 'canon',
    model: 'imageFORMULA DR-C225',
    name: 'اسکنر اسناد کانن مدل imageFORMULA DR-C225',
    sku: 'CN-DRC225',
    category: 'scanner',
    priceType: 'fixed',
    price: 38700000,
    stockStatus: 'in_stock',
    images: img('scanner'),
    shortDescription:
      'اسکنر اسناد جمع‌وجور با شارژر خودکار ۳۰ برگی، ایده‌آل برای دیجیتال‌سازی بایگانی اداری.',
    keyFeatures: ['اسکن ۲۵ برگ در دقیقه', 'ADF ۳۰ برگی', 'اسکن دورو در یک عبور'],
    specs: [
      { key: 'سرعت اسکن', value: '25 ppm / 50 ipm', group: 'عملکرد', isTechnical: true },
      { key: 'رزولوشن نوری', value: '600 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'ظرفیت ADF', value: '۳۰ برگ', group: 'کاغذ' },
      { key: 'اسکن دورو', value: 'یک‌عبوره', group: 'عملکرد' },
      { key: 'اتصالات', value: 'USB 2.0', group: 'اتصالات', isTechnical: true },
    ],
    usageClass: 'office',
    warrantyMonths: 24,
    condition: 'new',
    isFeatured: true,
    createdAt: '2026-05-30',
  },
  {
    id: 's-002',
    slug: 'epson-perfection-v39',
    brand: 'epson',
    model: 'Perfection V39',
    name: 'اسکنر رومیزی اپسون مدل Perfection V39',
    sku: 'EP-V39',
    category: 'scanner',
    priceType: 'fixed',
    price: 9800000,
    stockStatus: 'in_stock',
    images: img('scanner'),
    shortDescription: 'اسکنر تخت سبک با رزولوشن بالا، مناسب اسکن عکس و اسناد در دفاتر کوچک.',
    keyFeatures: ['رزولوشن ۴۸۰۰ dpi', 'بدون نیاز به آداپتور', 'طراحی فوق‌باریک'],
    specs: [
      { key: 'رزولوشن نوری', value: '4800 × 4800 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'نوع اسکنر', value: 'تخت (Flatbed)', group: 'عملکرد' },
      { key: 'حداکثر اندازه', value: 'A4 / Letter', group: 'کاغذ', isTechnical: true },
      { key: 'اتصالات', value: 'USB 2.0 (تغذیه از پورت)', group: 'اتصالات', isTechnical: true },
    ],
    usageClass: 'home',
    warrantyMonths: 12,
    condition: 'new',
    createdAt: '2026-04-14',
  },
  {
    id: 's-003',
    slug: 'ricoh-fi-7160',
    brand: 'ricoh',
    model: 'fi-7160',
    name: 'اسکنر پرسرعت ریکو مدل fi-7160',
    sku: 'RC-FI7160',
    category: 'scanner',
    priceType: 'quote_only',
    stockStatus: 'on_request',
    images: img('scanner'),
    shortDescription:
      'اسکنر حرفه‌ای اسناد با سرعت بسیار بالا و تشخیص هوشمند خطای تغذیه، مخصوص بایگانی سازمانی.',
    keyFeatures: ['اسکن ۶۰ برگ در دقیقه', 'ADF ۸۰ برگی', 'تشخیص اولتراسونیک تغذیهٔ دوتایی'],
    specs: [
      { key: 'سرعت اسکن', value: '60 ppm / 120 ipm', group: 'عملکرد', isTechnical: true },
      { key: 'رزولوشن نوری', value: '600 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'ظرفیت ADF', value: '۸۰ برگ', group: 'کاغذ' },
      { key: 'چرخهٔ کاری روزانه', value: '4,000 برگ', group: 'عملکرد', isTechnical: true },
      { key: 'اتصالات', value: 'USB 3.0', group: 'اتصالات', isTechnical: true },
    ],
    usageClass: 'enterprise',
    warrantyMonths: 24,
    condition: 'new',
    createdAt: '2026-06-25',
  },
  {
    id: 's-004',
    slug: 'hp-scanjet-pro-2000-s2',
    brand: 'hp',
    model: 'ScanJet Pro 2000 s2',
    name: 'اسکنر اسناد اچ‌پی مدل ScanJet Pro 2000 s2',
    sku: 'HP-SJ2000S2',
    category: 'scanner',
    priceType: 'fixed',
    price: 27500000,
    stockStatus: 'low_stock',
    images: img('scanner'),
    shortDescription: 'اسکنر شیت‌فید مقرون‌به‌صرفه با سرعت مناسب برای دفاتر با حجم اسناد متوسط.',
    keyFeatures: ['اسکن ۳۵ برگ در دقیقه', 'ADF ۵۰ برگی', 'نرم‌افزار OCR همراه'],
    specs: [
      { key: 'سرعت اسکن', value: '35 ppm / 70 ipm', group: 'عملکرد', isTechnical: true },
      { key: 'رزولوشن نوری', value: '600 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'ظرفیت ADF', value: '۵۰ برگ', group: 'کاغذ' },
      { key: 'اتصالات', value: 'USB 3.0', group: 'اتصالات', isTechnical: true },
    ],
    usageClass: 'office',
    warrantyMonths: 12,
    condition: 'new',
    createdAt: '2026-05-05',
  },

  // ═══════════════ دستگاه کپی ═══════════════
  {
    id: 'k-001',
    slug: 'konica-minolta-bizhub-266',
    brand: 'konica-minolta',
    model: 'bizhub 266',
    name: 'دستگاه کپی چندکاره کونیکا مینولتا مدل bizhub 266',
    sku: 'KM-BH266',
    category: 'copier',
    priceType: 'quote_only',
    stockStatus: 'on_request',
    images: img('copier'),
    shortDescription:
      'کپی‌پرینتر اداری تک‌رنگ با سرعت ۲۶ برگ در دقیقه و پنل لمسی، مناسب ادارات پرتردد.',
    keyFeatures: ['کپی و چاپ ۲۶ صفحه در دقیقه', 'پنل لمسی ۷ اینچ', 'اسکن رنگی شبکه'],
    specs: [
      { key: 'سرعت کپی', value: '26 ppm', group: 'عملکرد', isTechnical: true },
      { key: 'رزولوشن', value: '600 × 600 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'حافظه', value: '2 GB', group: 'عملکرد', isTechnical: true },
      { key: 'نمایشگر', value: 'لمسی ۷ اینچ', group: 'رابط کاربری' },
      { key: 'ظرفیت کاغذ', value: '۱٬۱۰۰ برگ (قابل ارتقا)', group: 'کاغذ' },
      { key: 'اتصالات', value: 'Ethernet، USB', group: 'اتصالات', isTechnical: true },
    ],
    technology: 'laser',
    colorSupport: 'mono',
    usageClass: 'enterprise',
    warrantyMonths: 12,
    condition: 'new',
    consumables: ['c-007'],
    isFeatured: true,
    createdAt: '2026-06-10',
  },
  {
    id: 'k-002',
    slug: 'ricoh-mp-2014d',
    brand: 'ricoh',
    model: 'MP 2014D',
    name: 'دستگاه کپی ریکو مدل MP 2014D',
    sku: 'RC-MP2014D',
    category: 'copier',
    priceType: 'fixed',
    price: 89000000,
    stockStatus: 'in_stock',
    images: img('copier'),
    shortDescription:
      'کپی‌پرینتر جمع‌وجور با چاپ دورو استاندارد، گزینه‌ای اقتصادی برای دفاتر متوسط.',
    keyFeatures: ['کپی ۲۰ صفحه در دقیقه', 'چاپ دورو استاندارد', 'مصرف انرژی پایین'],
    specs: [
      { key: 'سرعت کپی', value: '20 ppm', group: 'عملکرد', isTechnical: true },
      { key: 'رزولوشن', value: '600 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'زمان گرم شدن', value: 'کمتر از ۲۰ ثانیه', group: 'عملکرد' },
      { key: 'ظرفیت کاغذ', value: '۶۰۰ برگ', group: 'کاغذ' },
    ],
    technology: 'laser',
    colorSupport: 'mono',
    usageClass: 'office',
    warrantyMonths: 12,
    condition: 'new',
    consumables: ['c-008'],
    isBestSeller: true,
    createdAt: '2026-05-19',
  },
  {
    id: 'k-003',
    slug: 'canon-imagerunner-2425',
    brand: 'canon',
    model: 'imageRUNNER 2425',
    name: 'دستگاه کپی چندکاره کانن مدل imageRUNNER 2425',
    sku: 'CN-IR2425',
    category: 'copier',
    priceType: 'quote_only',
    stockStatus: 'on_request',
    images: img('copier'),
    shortDescription:
      'کپی‌پرینتر A3 چندکاره با قابلیت اسکن رنگی و مدیریت کاربران، مناسب سازمان‌های بزرگ.',
    keyFeatures: ['پشتیبانی از کاغذ A3', 'اسکن رنگی', 'مدیریت دسترسی کاربران'],
    specs: [
      { key: 'سرعت کپی', value: '25 ppm', group: 'عملکرد', isTechnical: true },
      { key: 'حداکثر اندازه', value: 'A3', group: 'کاغذ', isTechnical: true },
      { key: 'رزولوشن', value: '1200 × 1200 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'نمایشگر', value: 'لمسی ۵ اینچ', group: 'رابط کاربری' },
      { key: 'اتصالات', value: 'Ethernet، USB، Wi-Fi (اختیاری)', group: 'اتصالات', isTechnical: true },
    ],
    technology: 'laser',
    colorSupport: 'mono',
    usageClass: 'enterprise',
    warrantyMonths: 18,
    condition: 'new',
    createdAt: '2026-07-08',
  },
  {
    id: 'k-004',
    slug: 'konica-minolta-bizhub-227-refurb',
    brand: 'konica-minolta',
    model: 'bizhub 227',
    name: 'دستگاه کپی بازسازی‌شده کونیکا مینولتا مدل bizhub 227',
    sku: 'KM-BH227-R',
    category: 'copier',
    priceType: 'fixed',
    price: 62000000,
    compareAtPrice: 78000000,
    stockStatus: 'low_stock',
    images: img('copier'),
    shortDescription:
      'دستگاه کپی بازسازی‌شده با تست کامل فنی و ضمانت، گزینه‌ای اقتصادی با کارایی سازمانی.',
    keyFeatures: ['بازسازی و تست کامل', 'ضمانت ۶ ماهه', 'سرعت ۲۲ صفحه در دقیقه'],
    specs: [
      { key: 'سرعت کپی', value: '22 ppm', group: 'عملکرد', isTechnical: true },
      { key: 'وضعیت دستگاه', value: 'بازسازی‌شده و تست‌شده', group: 'عمومی' },
      { key: 'رزولوشن', value: '600 × 600 dpi', group: 'عملکرد', isTechnical: true },
      { key: 'ظرفیت کاغذ', value: '۱٬۱۰۰ برگ', group: 'کاغذ' },
    ],
    technology: 'laser',
    colorSupport: 'mono',
    usageClass: 'office',
    warrantyMonths: 6,
    condition: 'refurbished',
    createdAt: '2026-04-02',
  },

  // ═══════════════ فکس ═══════════════
  {
    id: 'f-001',
    slug: 'panasonic-kx-ft987',
    brand: 'panasonic',
    model: 'KX-FT987',
    name: 'دستگاه فکس حرارتی پاناسونیک مدل KX-FT987',
    sku: 'PN-FT987',
    category: 'fax',
    priceType: 'fixed',
    price: 7900000,
    stockStatus: 'in_stock',
    images: img('fax'),
    shortDescription:
      'فکس حرارتی با تلفن بی‌سیم و منشی تلفنی دیجیتال، مناسب دفاتر کوچک و مطب‌ها.',
    keyFeatures: ['تلفن بی‌سیم همراه', 'منشی تلفنی دیجیتال', 'حافظهٔ ۱۰۰ شماره'],
    specs: [
      { key: 'نوع چاپ', value: 'حرارتی (کاغذ رول)', group: 'عملکرد' },
      { key: 'سرعت مودم', value: '9.6 Kbps', group: 'عملکرد', isTechnical: true },
      { key: 'حافظهٔ شماره', value: '۱۰۰ شماره', group: 'عملکرد' },
      { key: 'منشی تلفنی', value: 'دیجیتال، ۱۵ دقیقه', group: 'عملکرد' },
    ],
    technology: 'thermal',
    colorSupport: 'mono',
    usageClass: 'home',
    warrantyMonths: 12,
    condition: 'new',
    createdAt: '2026-03-22',
  },
  {
    id: 'f-002',
    slug: 'brother-fax-2840',
    brand: 'brother',
    model: 'FAX-2840',
    name: 'دستگاه فکس لیزری برادر مدل FAX-2840',
    sku: 'BR-FAX2840',
    category: 'fax',
    priceType: 'fixed',
    price: 16800000,
    stockStatus: 'in_stock',
    images: img('fax'),
    shortDescription:
      'فکس لیزری با کیفیت چاپ بالا و شارژر خودکار ۲۰ برگی، مناسب ادارات با مکاتبات زیاد.',
    keyFeatures: ['چاپ لیزری روی کاغذ معمولی', 'ADF ۲۰ برگی', 'حافظهٔ ۴۰۰ صفحه'],
    specs: [
      { key: 'نوع چاپ', value: 'لیزری', group: 'عملکرد' },
      { key: 'سرعت مودم', value: '33.6 Kbps', group: 'عملکرد', isTechnical: true },
      { key: 'ظرفیت ADF', value: '۲۰ برگ', group: 'کاغذ' },
      { key: 'حافظهٔ دریافت', value: '۴۰۰ صفحه', group: 'عملکرد' },
    ],
    technology: 'laser',
    colorSupport: 'mono',
    usageClass: 'office',
    warrantyMonths: 18,
    condition: 'new',
    consumables: ['c-005'],
    createdAt: '2026-04-28',
  },

  // ═══════════════ مواد مصرفی ═══════════════
  {
    id: 'c-001',
    slug: 'canon-cartridge-303-toner',
    brand: 'canon',
    model: 'Cartridge 303',
    name: 'کارتریج تونر مشکی کانن مدل Cartridge 303',
    sku: 'CN-CRG303',
    category: 'consumables',
    subCategory: 'تونر',
    priceType: 'fixed',
    price: 1850000,
    stockStatus: 'in_stock',
    images: img('consumables'),
    shortDescription: 'کارتریج تونر اورجینال کانن با راندمان ۲٬۰۰۰ صفحه، سازگار با سری LBP-2900.',
    keyFeatures: ['راندمان ۲٬۰۰۰ صفحه', 'اورجینال کانن', 'نصب آسان'],
    specs: [
      { key: 'راندمان', value: '2,000 صفحه', group: 'عملکرد', isTechnical: true },
      { key: 'رنگ', value: 'مشکی', group: 'عمومی' },
      { key: 'نوع', value: 'اورجینال', group: 'عمومی' },
      { key: 'پوشش استاندارد', value: '۵٪ صفحه', group: 'عملکرد' },
    ],
    condition: 'new',
    warrantyMonths: 6,
    compatibleWith: ['i-SENSYS LBP-2900', 'i-SENSYS LBP-3000'],
    isBestSeller: true,
    createdAt: '2026-06-14',
  },
  {
    id: 'c-002',
    slug: 'canon-cartridge-303-drum',
    brand: 'canon',
    model: 'Drum Unit 303',
    name: 'درام یونیت کانن مدل Drum Unit 303',
    sku: 'CN-DRM303',
    category: 'consumables',
    subCategory: 'درام',
    priceType: 'fixed',
    price: 2650000,
    stockStatus: 'low_stock',
    images: img('consumables'),
    shortDescription: 'درام یونیت با کیفیت بالا و عمر مفید ۱۲٬۰۰۰ صفحه برای پرینترهای سری LBP.',
    keyFeatures: ['عمر مفید ۱۲٬۰۰۰ صفحه', 'کیفیت چاپ پایدار', 'تعویض بدون ابزار'],
    specs: [
      { key: 'عمر مفید', value: '12,000 صفحه', group: 'عملکرد', isTechnical: true },
      { key: 'نوع', value: 'درام یونیت', group: 'عمومی' },
    ],
    condition: 'new',
    warrantyMonths: 6,
    compatibleWith: ['i-SENSYS LBP-2900', 'i-SENSYS LBP-3000'],
    createdAt: '2026-05-27',
  },
  {
    id: 'c-003',
    slug: 'hp-58a-toner-cf258a',
    brand: 'hp',
    model: 'CF258A (58A)',
    name: 'کارتریج تونر مشکی اچ‌پی مدل 58A کد CF258A',
    sku: 'HP-CF258A',
    category: 'consumables',
    subCategory: 'تونر',
    priceType: 'fixed',
    price: 4300000,
    compareAtPrice: 4800000,
    stockStatus: 'in_stock',
    images: img('consumables'),
    shortDescription:
      'تونر اورجینال اچ‌پی با راندمان ۳٬۰۰۰ صفحه، مخصوص چاپگرهای سری LaserJet Pro M404.',
    keyFeatures: ['راندمان ۳٬۰۰۰ صفحه', 'تراشهٔ هوشمند', 'اورجینال با هولوگرام'],
    specs: [
      { key: 'راندمان', value: '3,000 صفحه', group: 'عملکرد', isTechnical: true },
      { key: 'رنگ', value: 'مشکی', group: 'عمومی' },
      { key: 'نوع', value: 'اورجینال', group: 'عمومی' },
    ],
    condition: 'new',
    warrantyMonths: 6,
    compatibleWith: ['LaserJet Pro M404dn', 'LaserJet Pro MFP M428fdn'],
    isBestSeller: true,
    isFeatured: true,
    createdAt: '2026-06-30',
  },
  {
    id: 'c-004',
    slug: 'epson-003-ink-bottle-black',
    brand: 'epson',
    model: 'T00V1 (003)',
    name: 'جوهر مخزن اپسون مدل 003 رنگ مشکی',
    sku: 'EP-T00V1',
    category: 'consumables',
    subCategory: 'جوهر',
    priceType: 'fixed',
    price: 520000,
    stockStatus: 'in_stock',
    images: img('consumables'),
    shortDescription: 'بطری جوهر اورجینال ۶۵ میلی‌لیتری با راندمان تا ۷٬۵۰۰ صفحه برای سری EcoTank.',
    keyFeatures: ['حجم ۶۵ میلی‌لیتر', 'راندمان تا ۷٬۵۰۰ صفحه', 'سرریز‌نشدنی'],
    specs: [
      { key: 'حجم', value: '65 ml', group: 'عمومی', isTechnical: true },
      { key: 'راندمان', value: '7,500 صفحه', group: 'عملکرد', isTechnical: true },
      { key: 'رنگ', value: 'مشکی', group: 'عمومی' },
    ],
    condition: 'new',
    compatibleWith: ['EcoTank L3250', 'EcoTank L3210'],
    isBestSeller: true,
    createdAt: '2026-07-03',
  },
  {
    id: 'c-005',
    slug: 'brother-tn-2411-toner',
    brand: 'brother',
    model: 'TN-2411',
    name: 'کارتریج تونر برادر مدل TN-2411',
    sku: 'BR-TN2411',
    category: 'consumables',
    subCategory: 'تونر',
    priceType: 'fixed',
    price: 2100000,
    stockStatus: 'in_stock',
    images: img('consumables'),
    shortDescription: 'تونر استاندارد برادر با راندمان ۱٬۲۰۰ صفحه برای چاپگرهای سری HL-L2xxx.',
    keyFeatures: ['راندمان ۱٬۲۰۰ صفحه', 'سازگار با سری L2000', 'کیفیت چاپ یکنواخت'],
    specs: [
      { key: 'راندمان', value: '1,200 صفحه', group: 'عملکرد', isTechnical: true },
      { key: 'رنگ', value: 'مشکی', group: 'عمومی' },
    ],
    condition: 'new',
    compatibleWith: ['HL-L2375DW', 'FAX-2840'],
    createdAt: '2026-05-11',
  },
  {
    id: 'c-006',
    slug: 'hp-415a-toner-set-color',
    brand: 'hp',
    model: 'W2030A (415A)',
    name: 'ست کارتریج رنگی اچ‌پی مدل 415A',
    sku: 'HP-W2030A-SET',
    category: 'consumables',
    subCategory: 'تونر رنگی',
    priceType: 'quote_only',
    stockStatus: 'on_request',
    images: img('consumables'),
    shortDescription:
      'ست کامل چهار کارتریج رنگی اورجینال برای چاپگرهای لیزری رنگی سری Color LaserJet Pro.',
    keyFeatures: ['ست کامل چهاررنگ', 'راندمان ۲٬۱۰۰ صفحه هر کارتریج', 'اورجینال'],
    specs: [
      { key: 'تعداد', value: '۴ عدد (مشکی، فیروزه‌ای، ارغوانی، زرد)', group: 'عمومی' },
      { key: 'راندمان', value: '2,100 صفحه (هر کارتریج)', group: 'عملکرد', isTechnical: true },
    ],
    condition: 'new',
    compatibleWith: ['Color LaserJet Pro M454dw'],
    createdAt: '2026-06-21',
  },
  {
    id: 'c-007',
    slug: 'konica-minolta-tn-323-toner',
    brand: 'konica-minolta',
    model: 'TN-323',
    name: 'تونر کونیکا مینولتا مدل TN-323',
    sku: 'KM-TN323',
    category: 'consumables',
    subCategory: 'تونر',
    priceType: 'fixed',
    price: 8900000,
    stockStatus: 'low_stock',
    images: img('consumables'),
    shortDescription: 'تونر پرظرفیت با راندمان ۲۳٬۰۰۰ صفحه برای دستگاه‌های کپی سری bizhub.',
    keyFeatures: ['راندمان ۲۳٬۰۰۰ صفحه', 'مخصوص bizhub', 'کاهش هزینهٔ هر برگ'],
    specs: [
      { key: 'راندمان', value: '23,000 صفحه', group: 'عملکرد', isTechnical: true },
      { key: 'رنگ', value: 'مشکی', group: 'عمومی' },
    ],
    condition: 'new',
    compatibleWith: ['bizhub 266', 'bizhub 227'],
    createdAt: '2026-06-05',
  },
  {
    id: 'c-008',
    slug: 'ricoh-sp-3710-toner',
    brand: 'ricoh',
    model: 'SP 3710',
    name: 'تونر ریکو مدل SP 3710',
    sku: 'RC-SP3710',
    category: 'consumables',
    subCategory: 'تونر',
    priceType: 'fixed',
    price: 5400000,
    stockStatus: 'in_stock',
    images: img('consumables'),
    shortDescription: 'کارتریج تونر پرظرفیت ریکو با راندمان ۷٬۰۰۰ صفحه برای دستگاه‌های سری MP.',
    keyFeatures: ['راندمان ۷٬۰۰۰ صفحه', 'تعویض سریع', 'سازگار با سری MP'],
    specs: [
      { key: 'راندمان', value: '7,000 صفحه', group: 'عملکرد', isTechnical: true },
      { key: 'رنگ', value: 'مشکی', group: 'عمومی' },
    ],
    condition: 'new',
    compatibleWith: ['MP 2014D'],
    createdAt: '2026-05-23',
  },

  // ═══════════════ قطعات یدکی ═══════════════
  {
    id: 'sp-001',
    slug: 'canon-fuser-unit-lbp2900',
    brand: 'canon',
    model: 'RM1-3717 Fuser',
    name: 'یونیت فیوزینگ کانن مدل RM1-3717',
    sku: 'CN-RM13717',
    category: 'spare-parts',
    subCategory: 'فیوزینگ',
    priceType: 'fixed',
    price: 3400000,
    stockStatus: 'in_stock',
    images: img('spare-parts'),
    shortDescription: 'یونیت فیوزینگ کامل برای رفع مشکل پخش نشدن تونر در پرینترهای سری LBP.',
    keyFeatures: ['قطعهٔ کامل و آمادهٔ نصب', 'تست‌شده', 'ضمانت ۳ ماهه'],
    specs: [
      { key: 'نوع قطعه', value: 'یونیت فیوزینگ', group: 'عمومی' },
      { key: 'ولتاژ', value: '220V', group: 'فنی', isTechnical: true },
    ],
    condition: 'new',
    warrantyMonths: 3,
    compatibleWith: ['i-SENSYS LBP-2900', 'i-SENSYS LBP-3000'],
    createdAt: '2026-04-09',
  },
  {
    id: 'sp-002',
    slug: 'hp-pickup-roller-m404',
    brand: 'hp',
    model: 'RM2-5741 Pickup Roller',
    name: 'غلتک کاغذکش اچ‌پی مدل RM2-5741',
    sku: 'HP-RM25741',
    category: 'spare-parts',
    subCategory: 'غلتک',
    priceType: 'fixed',
    price: 680000,
    stockStatus: 'in_stock',
    images: img('spare-parts'),
    shortDescription: 'غلتک کاغذکش برای رفع مشکل کاغذ نکشیدن و گیر کردن کاغذ در سری M404.',
    keyFeatures: ['رفع مشکل کاغذکشی', 'لاستیک باکیفیت', 'نصب آسان'],
    specs: [
      { key: 'نوع قطعه', value: 'غلتک کاغذکش (Pickup Roller)', group: 'عمومی' },
      { key: 'جنس', value: 'لاستیک فشرده', group: 'فنی' },
    ],
    condition: 'new',
    warrantyMonths: 3,
    compatibleWith: ['LaserJet Pro M404dn'],
    isBestSeller: true,
    createdAt: '2026-06-16',
  },
  {
    id: 'sp-003',
    slug: 'ricoh-transfer-belt-mp2014',
    brand: 'ricoh',
    model: 'D149-6001 Transfer Belt',
    name: 'تسمهٔ انتقال ریکو مدل D149-6001',
    sku: 'RC-D1496001',
    category: 'spare-parts',
    subCategory: 'تسمه',
    priceType: 'quote_only',
    stockStatus: 'on_request',
    images: img('spare-parts'),
    shortDescription: 'تسمهٔ انتقال تصویر برای دستگاه‌های کپی سری MP، تأمین به‌صورت سفارشی.',
    keyFeatures: ['قطعهٔ اورجینال', 'تأمین سفارشی', 'مشاورهٔ فنی رایگان'],
    specs: [
      { key: 'نوع قطعه', value: 'تسمهٔ انتقال (Transfer Belt)', group: 'عمومی' },
      { key: 'وضعیت تأمین', value: 'سفارشی — ۷ تا ۱۰ روز کاری', group: 'عمومی' },
    ],
    condition: 'new',
    compatibleWith: ['MP 2014D'],
    createdAt: '2026-03-30',
  },
  {
    id: 'sp-004',
    slug: 'konica-minolta-developer-dv-323',
    brand: 'konica-minolta',
    model: 'DV-323 Developer',
    name: 'دولوپر کونیکا مینولتا مدل DV-323',
    sku: 'KM-DV323',
    category: 'spare-parts',
    subCategory: 'دولوپر',
    priceType: 'fixed',
    price: 4750000,
    stockStatus: 'out_of_stock',
    images: img('spare-parts'),
    shortDescription: 'دولوپر اورجینال برای حفظ کیفیت چاپ در دستگاه‌های کپی سری bizhub.',
    keyFeatures: ['اورجینال', 'عمر مفید ۶۰۰٬۰۰۰ صفحه', 'حفظ کیفیت چاپ'],
    specs: [
      { key: 'نوع قطعه', value: 'دولوپر', group: 'عمومی' },
      { key: 'عمر مفید', value: '600,000 صفحه', group: 'عملکرد', isTechnical: true },
    ],
    condition: 'new',
    warrantyMonths: 3,
    compatibleWith: ['bizhub 266', 'bizhub 227'],
    createdAt: '2026-05-02',
  },
]
