import { Plus, X } from 'lucide-react';
import type { Attribute } from '../product-editor.types';
import { editorInputClass } from './EditorField';

export function AttributeTable({ attributes, onChange }: { attributes: Attribute[]; onChange: (attributes: Attribute[]) => void }) {
  const update = (id: string, patch: Partial<Attribute>) => onChange(attributes.map(attribute => attribute.id === id ? { ...attribute, ...patch } : attribute));
  const remove = (id: string) => onChange(attributes.filter(attribute => attribute.id !== id));
  const add = () => onChange([...attributes, { id: crypto.randomUUID(), group: 'جدید', name: '', value: '', unit: '', filterable: false, comparable: true, inSchema: true }]);

  return <div className="overflow-x-auto rounded-[var(--radius-md)] border border-[hsl(var(--border))]"><table className="w-full min-w-[780px] text-right text-xs"><thead className="text-[hsl(var(--muted-foreground))]"><tr>{['ویژگی', 'مقدار', 'واحد', 'فیلتر', 'مقایسه', 'اسکیما', ''].map(label => <th key={label} className="border-b border-[hsl(var(--border))] p-3 font-medium">{label}</th>)}</tr></thead><tbody>{attributes.map(attribute => <tr key={attribute.id}><td className="border-b border-[hsl(var(--border))] p-2"><input className={editorInputClass} value={attribute.name} onChange={e => update(attribute.id, { name: e.target.value })} /></td><td className="border-b border-[hsl(var(--border))] p-2"><input className={editorInputClass} value={attribute.value} onChange={e => update(attribute.id, { value: e.target.value })} /></td><td className="border-b border-[hsl(var(--border))] p-2"><input dir="ltr" className={editorInputClass} value={attribute.unit} onChange={e => update(attribute.id, { unit: e.target.value })} /></td>{(['filterable', 'comparable', 'inSchema'] as const).map(key => <td key={key} className="border-b border-[hsl(var(--border))] p-2 text-center"><input type="checkbox" checked={attribute[key]} onChange={e => update(attribute.id, { [key]: e.target.checked })} /></td>)}<td className="border-b border-[hsl(var(--border))] p-2"><button type="button" className="text-[hsl(var(--destructive))]" onClick={() => remove(attribute.id)}><X size={15} /></button></td></tr>)}</tbody></table><button type="button" onClick={add} className="m-2 flex w-[calc(100%-16px)] items-center justify-center gap-2 rounded-md border border-dashed border-[hsl(var(--border))] py-2 text-xs text-[hsl(var(--muted-foreground))] hover:border-[hsl(var(--primary))] hover:text-[hsl(var(--primary-bright))]"><Plus size={14} /> افزودن ویژگی</button></div>;
}
